apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/dark-tenure-428808-r3/locations/us-central1-c/clusters/cost-optimized-cluster-1 

