apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/dark-tenure-428808-r3/locations/us-central1-c/clusters/my-first-cluster-1

